env : "local" #dev, prod

http_server:
  address : "localhost:8082"
  jwt_secret :  ${JWT_SECRET}
  timeouts:
    request : 4s
    idle : 60s

postgres:
  host: localhost
  port: 5432
  database: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  pool_size: 10
  connections:
    max_life_time : 1h
    max_idle_time : 30min
    health_check_period : 1min
    timeout: 30s


