env : "local" #dev, prod

http_server:
  address : "0.0.0.0:8000"
  timeouts:
    request : 4s
    idle : 60s

postgres:
  host: db
  port: 5432
  pool_size: 10
  connection:
    max_life_time : 1h
    max_idle_time : 30m
    health_check_period : 1m
    timeout: 30s


